services:
  e-commerce:
    # image: node:lts-buster-slim
    container_name: e-commerce
    build: .
    volumes:
      - .:/e-commerce
      - /e-commerce/node_modules
    ports:
      - '3000:3000'
    
    # working_dir: /e-commerce
    # command: bash -c "npm i "
